### ISSUE TITLE
py-isort command broken

### ISSUE THREAD

**Issue by mithrandi** [paetzke/py-isort.el#8]
I'm not sure how I didn't notice this before, but 2950f3ff84478bbd64222c57c4af28afc9330468 broke the `py-isort` command. The `"r"` code specifies that the function should be called with the point and the mark as numeric arguments, but it does not actually take two arguments, so you get an error about "Wrong number of arguments". I'm not sure exactly what the intent was here, if you want to automatically detect that there's a region then the code would need to be written in a slightly different fashion.

**Comment by starenka** [comment]
same here :goberserk:

**Comment by dirkhusemann** [comment]
yep, can confirm that. d'oh.

**Comment by paetzke** [comment]
I should have read your message more carefully. I didn't thought of calling ```py-isort``` directly. I use ```py-isort-before-save``` and ```py-isort-region```.

I should rename ```py-isort``` and add a ```py-isort-buffer```.

**Comment by paetzke** [comment]
This is the patch https://github.com/paetzke/py-isort.el/tree/rename-functions

**Comment by paetzke** [comment]
I merged the patch.
